name: API Tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: Run API Tests
        run: npm run cy:api

      - name: Generate API Report
        run: npm run report:api

      - name: Upload API Report
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: cypress/reports/api/final